name: FirstRepo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5

  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  
  assets:
    - assets/images/intro.gif
    - assets/images/Capture.jpg
    - assets/images/done.gif
    - assets/images/green.jpg
    

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf

        

